;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cljr-slash
        clojure-align
        kill-region-or-backward-word
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-sexp
        sp-delete-char
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        sp-next-sexp
        sp-raise-sexp
        sp-remove-active-pair-overlay
        sp-splice-sexp-killing-backward
        sp-up-sexp
        vlt/clj-doto-print
        ))

(setq mc/cmds-to-run-once
      '(
        swiper
        ))
