;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        sp-backward-delete-char
        sp-backward-sexp
        sp-delete-char
        sp-forward-sexp
        sp-kill-word
        sp-raise-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ))
