;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        c-electric-colon
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        cider-switch-to-repl-buffer
        cljr-slash
        clojure-align
        counsel-M-x
        electric-newline-and-maybe-indent
        indent-for-tab-command
        kill-region-or-backward-word
        kmacro-end-or-call-macro
        markdown-outdent-or-delete
        nxml-electric-slash
        org-end-of-line
        org-yank
        pp-eval-expression
        prog-fill-reindent-defun
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-sexp
        sp-backward-up-sexp
        sp-delete-char
        sp-down-sexp
        sp-end-of-sexp
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        sp-next-sexp
        sp-raise-sexp
        sp-remove-active-pair-overlay
        sp-splice-sexp-killing-backward
        sp-split-sexp
        sp-up-sexp
        toggle-quotes
        transpose-sexps
        vlt/clj-doto-print
        wdired--self-insert
        yaml-electric-dash-and-dot
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        cider-eval-defun-at-point
        end-of-buffer
        mc--insert-number-and-increase
        org-self-insert-command
        swiper
        ))
